#!/bin/sh
printf '%s\n' \
'{"type":"begin","data":{"path":{"text":"a.txt"}}}' \
'{"type":"match","data":{"path":{"text":"a.txt"},"lines":{"text":"hitxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxfar\n"},"line_number":1,"submatches":[{"match":{"text":"hit"},"start":0,"end":3},{"match":{"text":"far"},"start":153,"end":156}]}}' \
'{"type":"match","data":{"path":{"text":"a.txt"},"lines":{"text":"hityyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyfar\n"},"line_number":2,"submatches":[{"match":{"text":"hit"},"start":0,"end":3},{"match":{"text":"far"},"start":153,"end":156}]}}' \
'{"type":"match","data":{"path":{"text":"a.txt"},"lines":{"text":"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzfar\n"},"line_number":3,"submatches":[{"match":{"text":"far"},"start":150,"end":153}]}}' \
'{"type":"match","data":{"path":{"text":"a.txt"},"lines":{"text":"xxxxxmidxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxfar\n"},"line_number":4,"submatches":[{"match":{"text":"mid"},"start":5,"end":8},{"match":{"text":"far"},"start":70,"end":73}]}}' \
'{"type":"end","data":{"path":{"text":"a.txt"},"binary_offset":null}}' \
'{"type":"summary","data":{}}'
exit 0
