#!/bin/sh
printf '%s\n' \
'{"type":"begin","data":{"path":{"text":"a.txt"}}}' \
'{"type":"match","data":{"path":{"text":"a.txt"},"lines":{"text":"hit a001\n"},"line_number":1,"submatches":[{"match":{"text":"hit"},"start":0,"end":3}]}}' \
'{"type":"match","data":{"path":{"text":"a.txt"},"lines":{"text":"hit a004\n"},"line_number":4,"submatches":[{"match":{"text":"hit"},"start":0,"end":3}]}}' \
'{"type":"end","data":{"path":{"text":"a.txt"},"binary_offset":null}}' \
'{"type":"begin","data":{"path":{"text":"b.txt"}}}' \
'{"type":"match","data":{"path":{"text":"b.txt"},"lines":{"text":"hit b002\n"},"line_number":2,"submatches":[{"match":{"text":"hit"},"start":0,"end":3}]}}' \
'{"type":"match","data":{"path":{"text":"b.txt"},"lines":{"text":"hit b005\n"},"line_number":5,"submatches":[{"match":{"text":"hit"},"start":0,"end":3}]}}' \
'{"type":"end","data":{"path":{"text":"b.txt"},"binary_offset":null}}' \
'{"type":"begin","data":{"path":{"text":"c.txt"}}}' \
'{"type":"match","data":{"path":{"text":"c.txt"},"lines":{"text":"hit c003\n"},"line_number":3,"submatches":[{"match":{"text":"hit"},"start":0,"end":3}]}}' \
'{"type":"end","data":{"path":{"text":"c.txt"},"binary_offset":null}}' \
'{"type":"summary","data":{}}'
exit 0
