#!/bin/bash
cd /home/chris/vrg/Notes/walkthroughs/012-04/code-walkthrough
echo "=== Initial view (offset 0, contentHeight = 23) ==="
python3 showlines.py "q"
echo ""
echo "=== After down (one row, offset 1) ==="
python3 showlines.py "$(printf '\x1b[B')q"
echo ""
echo "=== After d (half page = 11, offset 11) ==="
python3 showlines.py "dq"
echo ""
echo "=== After pgdn (full page = 23, offset 23) ==="
python3 showlines.py "$(printf '\x1b[6~')q"
echo ""
echo "=== EOF clamp: 3x pgdn (offset 69 -> clamped to 37) ==="
python3 showlines.py "$(printf '\x1b[6~\x1b[6~\x1b[6~')q"
echo ""
echo "=== down at EOF (no-op, stays at lines 38-60) ==="
python3 showlines.py "$(printf '\x1b[6~\x1b[6~\x1b[6~\x1b[B')q"
echo ""
echo "=== up at BOF (no-op, stays at lines 1-23) ==="
python3 showlines.py "$(printf '\x1b[A')q"
echo ""
echo "=== u (half page up from offset 23 -> offset 12) ==="
python3 showlines.py "$(printf '\x1b[6~u')q"
echo ""
echo "=== pgup (full page up from offset 23 -> offset 0) ==="
python3 showlines.py "$(printf '\x1b[6~\x1b[5~')q"
