#!/bin/sh
printf '%s\n' \
'{"type":"begin","data":{"path":{"text":"long.txt"}}}' \
'{"type":"match","data":{"path":{"text":"long.txt"},"lines":{"text":"hit 00005\n"},"line_number":5,"submatches":[{"match":{"text":"hit"},"start":0,"end":3}]}}' \
'{"type":"match","data":{"path":{"text":"long.txt"},"lines":{"text":"hit 00200\n"},"line_number":200,"submatches":[{"match":{"text":"hit"},"start":0,"end":3}]}}' \
'{"type":"match","data":{"path":{"text":"long.txt"},"lines":{"text":"hit 00210\n"},"line_number":210,"submatches":[{"match":{"text":"hit"},"start":0,"end":3}]}}' \
'{"type":"end","data":{"path":{"text":"long.txt"},"binary_offset":null}}' \
'{"type":"summary","data":{}}'
exit 0
