#!/bin/sh
cat <<'EOF'
{"type":"begin","data":{"path":{"text":"./a.txt"}}}
{"type":"match","data":{"path":{"text":"./a.txt"},"lines":{"bytes":"zIF4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eAo="},"line_number":1,"absolute_offset":0,"submatches":[{"match":{"bytes":"zIE="},"start":0,"end":2}]}}
{"type":"match","data":{"path":{"text":"./a.txt"},"lines":{"bytes":"YWIBzIFjZCB0aGUgbWFyayBzaXRzIG1pZC1saW5lCg=="},"line_number":2,"absolute_offset":0,"submatches":[{"match":{"bytes":"zIE="},"start":3,"end":5}]}}
{"type":"end","data":{"path":{"text":"./a.txt"},"binary_offset":null,"stats":{}}}
{"type":"summary","data":{"stats":{}}}
EOF
exit 0
